version: '3'
services:
  tomcat:
    build: .
    image: com.ragedunicorn/tomcat:1.0-stable
    ports:
      - "8080:8080"
    labels:
      com.ragedunicorn.tomcat.environment: "prod"
      com.ragedunicorn.tomcat.description: "Apache tomcat"
