version: '3'
services:
  tomcat:
    build: .
    image: com.ragedunicorn/tomcat:1.0-dev
    ports:
      - "8080:8080"
      - "60333:60333"
    environment:
      - CATALINA_OPTS="-agentlib:jdwp=transport=dt_socket,address=60333,server=y,suspend=n"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    labels:
      ch.dailylife.tomcat.environment: "dev"
      ch.dailylife.tomcat.description: "Apache tomcat"
