version: '3.6'
services:
  tomcat:
    build: .
    image: ragedunicorn/tomcat:${TOMCAT_TAG_VERSION}-stable
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.tomcat.environment: "prod"
      com.ragedunicorn.tomcat.description: "Apache tomcat"
