version: '3.8'
services:
  tomcat:
    image: ragedunicorn/tomcat:1.3.2-stable
    secrets:
      - com.ragedunicorn.tomcat.app_user
      - com.ragedunicorn.tomcat.app_user_password
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.tomcat.environment: "prod"
      com.ragedunicorn.tomcat.description: "Apache tomcat"
secrets:
  com.ragedunicorn.tomcat.app_user:
    external: true
  com.ragedunicorn.tomcat.app_user_password:
    external: true
