version: '3.4'
services:
  tomcat:
    image: ragedunicorn/tomcat:${TOMCAT_TAG_VERSION}-stable
    secrets:
      - com.ragedunicorn.tomcat.app_user
      - com.ragedunicorn.tomcat.app_user_password
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.tomcat.environment: "prod"
      com.ragedunicorn.tomcat.description: "Apache tomcat"
secrets:
  com.ragedunicorn.tomcat.app_user:
    external: true
  com.ragedunicorn.tomcat.app_user_password:
    external: true
